   name: Deploy to AWS Elastic Beanstalk

   on:
     push:
       branches: [ main ]

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2

       - name: Use Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '20.x'

       - name: Install dependencies
         run: yarn install

       - name: Run tests
         run: yarn test

       - name: Build application
         run: yarn build

       - name: Generate deployment package
         run: zip -r deploy.zip . -x '*.git*'

       - name: Deploy to EB
         uses: einaregilsson/beanstalk-deploy@v20
         with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           application_name: ${{ secrets.EB_APPLICATION_NAME }}
           environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
           version_label: ${{ github.sha }}
           region: ${{ secrets.AWS_REGION }}
           deployment_package: deploy.zip